semanticCube = dict()

#Int
semanticCube[("+", "INT", "INT")]        = "INT"
semanticCube[("-", "INT", "INT")]        = "INT"
semanticCube[("*", "INT", "INT")]        = "INT"
semanticCube[("/", "INT", "INT")]        = "INT"
semanticCube[("=", "INT", "INT")]        = "INT"
semanticCube[("==", "INT", "INT")]       = "BOOL"
semanticCube[("!=", "INT", "INT")]       = "BOOL"
semanticCube[("&", "INT", "INT")]        = "ERROR"
semanticCube[("|", "INT", "INT")]        = "ERROR"
semanticCube[("<", "INT", "INT")]        = "BOOL"
semanticCube[(">", "INT", "INT")]        = "BOOL"
semanticCube[("<=", "INT", "INT")]       = "BOOL"
semanticCube[(">=", "INT", "INT")]       = "BOOL"

semanticCube[("+", "INT", "FLOAT")]      = "FLOAT"
semanticCube[("-", "INT", "FLOAT")]      = "FLOAT"
semanticCube[("*", "INT", "FLOAT")]      = "FLOAT"
semanticCube[("/", "INT", "FLOAT")]      = "FLOAT"
semanticCube[("=", "INT", "FLOAT")]      = "INT"
semanticCube[("==", "INT", "FLOAT")]     = "BOOL"
semanticCube[("!=", "INT", "FLOAT")]     = "BOOL"
semanticCube[("&", "INT", "FLOAT")]      = "ERROR"
semanticCube[("|", "INT", "FLOAT")]      = "ERROR"
semanticCube[("<", "INT", "FLOAT")]      = "BOOL"
semanticCube[(">", "INT", "FLOAT")]      = "BOOL"
semanticCube[("<=", "INT", "FLOAT")]     = "BOOL"
semanticCube[(">=", "INT", "FLOAT")]     = "BOOL"

semanticCube[("+", "INT", "CHAR")]       = "ERROR"
semanticCube[("-", "INT", "CHAR")]       = "ERROR"
semanticCube[("*", "INT", "CHAR")]       = "ERROR"
semanticCube[("/", "INT", "CHAR")]       = "ERROR"
semanticCube[("=", "INT", "CHAR")]       = "ERROR"
semanticCube[("==", "INT", "CHAR")]      = "ERROR"
semanticCube[("!=", "INT", "CHAR")]      = "ERROR"
semanticCube[("&", "INT", "CHAR")]       = "ERROR"
semanticCube[("|", "INT", "CHAR")]       = "ERROR"
semanticCube[("<", "INT", "CHAR")]       = "ERROR"
semanticCube[(">", "INT", "CHAR")]       = "ERROR"
semanticCube[("<=", "INT", "CHAR")]      = "ERROR"
semanticCube[(">=", "INT", "CHAR")]      = "ERROR"

semanticCube[("+", "INT", "BOOL")]       = "ERROR"
semanticCube[("-", "INT", "BOOL")]       = "ERROR"
semanticCube[("*", "INT", "BOOL")]       = "ERROR"
semanticCube[("/", "INT", "BOOL")]       = "ERROR"
semanticCube[("=", "INT", "BOOL")]       = "ERROR"
semanticCube[("==", "INT", "BOOL")]      = "ERROR"
semanticCube[("!=", "INT", "BOOL")]      = "ERROR"
semanticCube[("&", "INT", "BOOL")]       = "ERROR"
semanticCube[("|", "INT", "BOOL")]       = "ERROR"
semanticCube[("<", "INT", "BOOL")]       = "ERROR"
semanticCube[(">", "INT", "BOOL")]       = "ERROR"
semanticCube[("<=", "INT", "BOOL")]      = "ERROR"
semanticCube[(">=", "INT", "BOOL")]      = "ERROR"

#Float
semanticCube[("+", "FLOAT", "INT")]      = "FLOAT"
semanticCube[("-", "FLOAT", "INT")]      = "FLOAT"
semanticCube[("*", "FLOAT", "INT")]      = "FLOAT"
semanticCube[("/", "FLOAT", "INT")]      = "FLOAT"
semanticCube[("=", "FLOAT", "INT")]      = "FLOAT"
semanticCube[("==", "FLOAT", "INT")]     = "BOOL"
semanticCube[("!=", "FLOAT", "INT")]     = "BOOL"
semanticCube[("&", "FLOAT", "INT")]      = "ERROR"
semanticCube[("|", "FLOAT", "INT")]      = "ERROR"
semanticCube[("<", "FLOAT", "INT")]      = "BOOL"
semanticCube[(">", "FLOAT", "INT")]      = "BOOL"
semanticCube[("<=", "FLOAT", "INT")]     = "BOOL"
semanticCube[(">=", "FLOAT", "INT")]     = "BOOL"

semanticCube[("+", "FLOAT", "FLOAT")]    = "FLOAT"
semanticCube[("-", "FLOAT", "FLOAT")]    = "FLOAT"
semanticCube[("*", "FLOAT", "FLOAT")]    = "FLOAT"
semanticCube[("/", "FLOAT", "FLOAT")]    = "FLOAT"
semanticCube[("=", "FLOAT", "FLOAT")]    = "FLOAT"
semanticCube[("==", "FLOAT", "FLOAT")]   = "BOOL"
semanticCube[("!=", "FLOAT", "FLOAT")]   = "BOOL"
semanticCube[("&", "FLOAT", "FLOAT")]    = "ERROR"
semanticCube[("|", "FLOAT", "FLOAT")]    = "ERROR"
semanticCube[("<", "FLOAT", "FLOAT")]    = "BOOL"
semanticCube[(">", "FLOAT", "FLOAT")]    = "BOOL"
semanticCube[("<=", "FLOAT", "FLOAT")]   = "BOOL"
semanticCube[(">=", "FLOAT", "FLOAT")]   = "BOOL"

semanticCube[("+", "FLOAT", "CHAR")]     = "ERROR"
semanticCube[("-", "FLOAT", "CHAR")]     = "ERROR"
semanticCube[("*", "FLOAT", "CHAR")]     = "ERROR"
semanticCube[("/", "FLOAT", "CHAR")]     = "ERROR"
semanticCube[("=", "FLOAT", "CHAR")]     = "ERROR"
semanticCube[("==", "FLOAT", "CHAR")]    = "ERROR"
semanticCube[("!=", "FLOAT", "CHAR")]    = "ERROR"
semanticCube[("&", "FLOAT", "CHAR")]     = "ERROR"
semanticCube[("|", "FLOAT", "CHAR")]     = "ERROR"
semanticCube[("<", "FLOAT", "CHAR")]     = "ERROR"
semanticCube[(">", "FLOAT", "CHAR")]     = "ERROR"
semanticCube[("<=", "FLOAT", "CHAR")]    = "ERROR"
semanticCube[(">=", "FLOAT", "CHAR")]    = "ERROR"

semanticCube[("+", "FLOAT", "BOOL")]     = "ERROR"
semanticCube[("-", "FLOAT", "BOOL")]     = "ERROR"
semanticCube[("*", "FLOAT", "BOOL")]     = "ERROR"
semanticCube[("/", "FLOAT", "BOOL")]     = "ERROR"
semanticCube[("=", "FLOAT", "BOOL")]     = "ERROR"
semanticCube[("==", "FLOAT", "BOOL")]    = "ERROR"
semanticCube[("!=", "FLOAT", "BOOL")]    = "ERROR"
semanticCube[("&", "FLOAT", "BOOL")]     = "ERROR"
semanticCube[("|", "FLOAT", "BOOL")]     = "ERROR"
semanticCube[("<", "FLOAT", "BOOL")]     = "ERROR"
semanticCube[(">", "FLOAT", "BOOL")]     = "ERROR"
semanticCube[("<=", "FLOAT", "BOOL")]    = "ERROR"
semanticCube[(">=", "FLOAT", "BOOL")]    = "ERROR"

#Char
semanticCube[("+", "CHAR", "INT")]       = "ERROR"
semanticCube[("-", "CHAR", "INT")]       = "ERROR"
semanticCube[("*", "CHAR", "INT")]       = "ERROR"
semanticCube[("/", "CHAR", "INT")]       = "ERROR"
semanticCube[("=", "CHAR", "INT")]       = "ERROR"
semanticCube[("==", "CHAR", "INT")]      = "ERROR"
semanticCube[("!=", "CHAR", "INT")]      = "ERROR"
semanticCube[("&", "CHAR", "INT")]       = "ERROR"
semanticCube[("|", "CHAR", "INT")]       = "ERROR"
semanticCube[("<", "CHAR", "INT")]       = "ERROR"
semanticCube[(">", "CHAR", "INT")]       = "ERROR"
semanticCube[("<=", "CHAR", "INT")]      = "ERROR"
semanticCube[(">=", "CHAR", "INT")]      = "ERROR"

semanticCube[("+", "CHAR", "FLOAT")]     = "ERROR"
semanticCube[("-", "CHAR", "FLOAT")]     = "ERROR"
semanticCube[("*", "CHAR", "FLOAT")]     = "ERROR"
semanticCube[("/", "CHAR", "FLOAT")]     = "ERROR"
semanticCube[("=", "CHAR", "FLOAT")]     = "ERROR"
semanticCube[("==", "CHAR", "FLOAT")]    = "ERROR"
semanticCube[("!=", "CHAR", "FLOAT")]    = "ERROR"
semanticCube[("&", "CHAR", "FLOAT")]     = "ERROR"
semanticCube[("|", "CHAR", "FLOAT")]     = "ERROR"
semanticCube[("<", "CHAR", "FLOAT")]     = "ERROR"
semanticCube[(">", "CHAR", "FLOAT")]     = "ERROR"
semanticCube[("<=", "CHAR", "FLOAT")]    = "ERROR"
semanticCube[(">=", "CHAR", "FLOAT")]    = "ERROR"

semanticCube[("+", "CHAR", "CHAR")]      = "ERROR"
semanticCube[("-", "CHAR", "CHAR")]      = "ERROR"
semanticCube[("*", "CHAR", "CHAR")]      = "ERROR"
semanticCube[("/", "CHAR", "CHAR")]      = "ERROR"
semanticCube[("=", "CHAR", "CHAR")]      = "CHAR"
semanticCube[("==", "CHAR", "CHAR")]     = "BOOL"
semanticCube[("!=", "CHAR", "CHAR")]     = "BOOL"
semanticCube[("&", "CHAR", "CHAR")]      = "ERROR"
semanticCube[("|", "CHAR", "CHAR")]      = "ERROR"
semanticCube[("<", "CHAR", "CHAR")]      = "ERROR"
semanticCube[(">", "CHAR", "CHAR")]      = "ERROR"
semanticCube[("<=", "CHAR", "CHAR")]     = "ERROR"
semanticCube[(">=", "CHAR", "CHAR")]     = "ERROR"

semanticCube[("+", "CHAR", "BOOL")]      = "ERROR"
semanticCube[("-", "CHAR", "BOOL")]      = "ERROR"
semanticCube[("*", "CHAR", "BOOL")]      = "ERROR"
semanticCube[("/", "CHAR", "BOOL")]      = "ERROR"
semanticCube[("=", "CHAR", "BOOL")]      = "ERROR"
semanticCube[("==", "CHAR", "BOOL")]     = "ERROR"
semanticCube[("!=", "CHAR", "BOOL")]     = "ERROR"
semanticCube[("&", "CHAR", "BOOL")]      = "ERROR"
semanticCube[("|", "CHAR", "BOOL")]      = "ERROR"
semanticCube[("<", "CHAR", "BOOL")]      = "ERROR"
semanticCube[(">", "CHAR", "BOOL")]      = "ERROR"
semanticCube[("<=", "CHAR", "BOOL")]     = "ERROR"
semanticCube[(">=", "CHAR", "BOOL")]     = "ERROR"

#Bool
semanticCube[("+", "BOOL", "INT")]       = "ERROR"
semanticCube[("-", "BOOL", "INT")]       = "ERROR"
semanticCube[("*", "BOOL", "INT")]       = "ERROR"
semanticCube[("/", "BOOL", "INT")]       = "ERROR"
semanticCube[("=", "BOOL", "INT")]       = "ERROR"
semanticCube[("==", "BOOL", "INT")]      = "ERROR"
semanticCube[("!=", "BOOL", "INT")]      = "ERROR"
semanticCube[("&", "BOOL", "INT")]       = "ERROR"
semanticCube[("|", "BOOL", "INT")]       = "ERROR"
semanticCube[("<", "BOOL", "INT")]       = "ERROR"
semanticCube[(">", "BOOL", "INT")]       = "ERROR"
semanticCube[("<=", "BOOL", "INT")]      = "ERROR"
semanticCube[(">=", "BOOL", "INT")]      = "ERROR"

semanticCube[("+", "BOOL", "FLOAT")]     = "ERROR"
semanticCube[("-", "BOOL", "FLOAT")]     = "ERROR"
semanticCube[("*", "BOOL", "FLOAT")]     = "ERROR"
semanticCube[("/", "BOOL", "FLOAT")]     = "ERROR"
semanticCube[("=", "BOOL", "FLOAT")]     = "ERROR"
semanticCube[("==", "BOOL", "FLOAT")]    = "ERROR"
semanticCube[("!=", "BOOL", "FLOAT")]    = "ERROR"
semanticCube[("&", "BOOL", "FLOAT")]     = "ERROR"
semanticCube[("|", "BOOL", "FLOAT")]     = "ERROR"
semanticCube[("<", "BOOL", "FLOAT")]     = "ERROR"
semanticCube[(">", "BOOL", "FLOAT")]     = "ERROR"
semanticCube[("<=", "BOOL", "FLOAT")]    = "ERROR"
semanticCube[(">=", "BOOL", "FLOAT")]    = "ERROR"

semanticCube[("+", "BOOL", "CHAR")]      = "ERROR"
semanticCube[("-", "BOOL", "CHAR")]      = "ERROR"
semanticCube[("*", "BOOL", "CHAR")]      = "ERROR"
semanticCube[("/", "BOOL", "CHAR")]      = "ERROR"
semanticCube[("=", "BOOL", "CHAR")]      = "ERROR"
semanticCube[("==", "BOOL", "CHAR")]     = "ERROR"
semanticCube[("!=", "BOOL", "CHAR")]     = "ERROR"
semanticCube[("&", "BOOL", "CHAR")]      = "ERROR"
semanticCube[("|", "BOOL", "CHAR")]      = "ERROR"
semanticCube[("<", "BOOL", "CHAR")]      = "ERROR"
semanticCube[(">", "BOOL", "CHAR")]      = "ERROR"
semanticCube[("<=", "BOOL", "CHAR")]     = "ERROR"
semanticCube[(">=", "BOOL", "CHAR")]     = "ERROR"

semanticCube[("+", "BOOL", "BOOL")]      = "ERROR"
semanticCube[("-", "BOOL", "BOOL")]      = "ERROR"
semanticCube[("*", "BOOL", "BOOL")]      = "ERROR"
semanticCube[("/", "BOOL", "BOOL")]      = "ERROR"
semanticCube[("=", "BOOL", "BOOL")]      = "BOOL"
semanticCube[("==", "BOOL", "BOOL")]     = "BOOL"
semanticCube[("!=", "BOOL", "BOOL")]     = "BOOL"
semanticCube[("&", "BOOL", "BOOL")]      = "BOOL"
semanticCube[("|", "BOOL", "BOOL")]      = "BOOL"
semanticCube[("<", "BOOL", "BOOL")]      = "ERROR"
semanticCube[(">", "BOOL", "BOOL")]      = "ERROR"
semanticCube[("<=", "BOOL", "BOOL")]     = "ERROR"
semanticCube[(">=", "BOOL", "BOOL")]     = "ERROR"

def resultingType(p1, p2, p3):
    key = (p1, p2, p3)
    if key in semanticCube:
        return semanticCube[key]
    else:
        return "Error"