semanticCube = dict()

semanticCube[("+", "int", "int")]        = "int"
semanticCube[("-", "int", "int")]        = "int"
semanticCube[("*", "int", "int")]        = "int"
semanticCube[("/", "int", "int")]        = "int"
semanticCube[("=", "int", "int")]        = "int"
semanticCube[("==", "int", "int")]       = "bool"
semanticCube[("!=", "int", "int")]       = "bool"
semanticCube[("&", "int", "int")]        = "ERROR"
semanticCube[("|", "int", "int")]        = "ERROR"
semanticCube[("<", "int", "int")]        = "bool"
semanticCube[(">", "int", "int")]        = "bool"
semanticCube[("<=", "int", "int")]       = "bool"
semanticCube[(">=", "int", "int")]       = "bool"

semanticCube[("+", "int", "float")]      = "float"
semanticCube[("-", "int", "float")]      = "float"
semanticCube[("*", "int", "float")]      = "float"
semanticCube[("/", "int", "float")]      = "float"
semanticCube[("=", "int", "float")]      = "int"
semanticCube[("==", "int", "float")]     = "bool"
semanticCube[("!=", "int", "float")]     = "bool"
semanticCube[("&", "int", "float")]      = "ERROR"
semanticCube[("|", "int", "float")]      = "ERROR"
semanticCube[("<", "int", "float")]      = "bool"
semanticCube[(">", "int", "float")]      = "bool"
semanticCube[("<=", "int", "float")]     = "bool"
semanticCube[(">=", "int", "float")]     = "bool"

semanticCube[("+", "int", "char")]       = "ERROR"
semanticCube[("-", "int", "char")]       = "ERROR"
semanticCube[("*", "int", "char")]       = "ERROR"
semanticCube[("/", "int", "char")]       = "ERROR"
semanticCube[("=", "int", "char")]       = "ERROR"
semanticCube[("==", "int", "char")]      = "ERROR"
semanticCube[("!=", "int", "char")]      = "ERROR"
semanticCube[("&", "int", "char")]       = "ERROR"
semanticCube[("|", "int", "char")]       = "ERROR"
semanticCube[("<", "int", "char")]       = "ERROR"
semanticCube[(">", "int", "char")]       = "ERROR"
semanticCube[("<=", "int", "char")]      = "ERROR"
semanticCube[(">=", "int", "char")]      = "ERROR"

semanticCube[("+", "int", "bool")]       = "ERROR"
semanticCube[("-", "int", "bool")]       = "ERROR"
semanticCube[("*", "int", "bool")]       = "ERROR"
semanticCube[("/", "int", "bool")]       = "ERROR"
semanticCube[("=", "int", "bool")]       = "ERROR"
semanticCube[("==", "int", "bool")]      = "ERROR"
semanticCube[("!=", "int", "bool")]      = "ERROR"
semanticCube[("&", "int", "bool")]       = "ERROR"
semanticCube[("|", "int", "bool")]       = "ERROR"
semanticCube[("<", "int", "bool")]       = "ERROR"
semanticCube[(">", "int", "bool")]       = "ERROR"
semanticCube[("<=", "int", "bool")]      = "ERROR"
semanticCube[(">=", "int", "bool")]      = "ERROR"

semanticCube[("+", "float", "int")]      = "float"
semanticCube[("-", "float", "int")]      = "float"
semanticCube[("*", "float", "int")]      = "float"
semanticCube[("/", "float", "int")]      = "float"
semanticCube[("=", "float", "int")]      = "float"
semanticCube[("==", "float", "int")]     = "bool"
semanticCube[("!=", "float", "int")]     = "bool"
semanticCube[("&", "float", "int")]      = "ERROR"
semanticCube[("|", "float", "int")]      = "ERROR"
semanticCube[("<", "float", "int")]      = "bool"
semanticCube[(">", "float", "int")]      = "bool"
semanticCube[("<=", "float", "int")]     = "bool"
semanticCube[(">=", "float", "int")]     = "bool"

semanticCube[("+", "float", "float")]    = "float"
semanticCube[("-", "float", "float")]    = "float"
semanticCube[("*", "float", "float")]    = "float"
semanticCube[("/", "float", "float")]    = "float"
semanticCube[("=", "float", "float")]    = "float"
semanticCube[("==", "float", "float")]   = "bool"
semanticCube[("!=", "float", "float")]   = "bool"
semanticCube[("&", "float", "float")]    = "ERROR"
semanticCube[("|", "float", "float")]    = "ERROR"
semanticCube[("<", "float", "float")]    = "bool"
semanticCube[(">", "float", "float")]    = "bool"
semanticCube[("<=", "float", "float")]   = "bool"
semanticCube[(">=", "float", "float")]   = "bool"

semanticCube[("+", "float", "char")]     = "ERROR"
semanticCube[("-", "float", "char")]     = "ERROR"
semanticCube[("*", "float", "char")]     = "ERROR"
semanticCube[("/", "float", "char")]     = "ERROR"
semanticCube[("=", "float", "char")]     = "ERROR"
semanticCube[("==", "float", "char")]    = "ERROR"
semanticCube[("!=", "float", "char")]    = "ERROR"
semanticCube[("&", "float", "char")]     = "ERROR"
semanticCube[("|", "float", "char")]     = "ERROR"
semanticCube[("<", "float", "char")]     = "ERROR"
semanticCube[(">", "float", "char")]     = "ERROR"
semanticCube[("<=", "float", "char")]    = "ERROR"
semanticCube[(">=", "float", "char")]    = "ERROR"

semanticCube[("+", "float", "bool")]     = "ERROR"
semanticCube[("-", "float", "bool")]     = "ERROR"
semanticCube[("*", "float", "bool")]     = "ERROR"
semanticCube[("/", "float", "bool")]     = "ERROR"
semanticCube[("=", "float", "bool")]     = "ERROR"
semanticCube[("==", "float", "bool")]    = "ERROR"
semanticCube[("!=", "float", "bool")]    = "ERROR"
semanticCube[("&", "float", "bool")]     = "ERROR"
semanticCube[("|", "float", "bool")]     = "ERROR"
semanticCube[("<", "float", "bool")]     = "ERROR"
semanticCube[(">", "float", "bool")]     = "ERROR"
semanticCube[("<=", "float", "bool")]    = "ERROR"
semanticCube[(">=", "float", "bool")]    = "ERROR"

semanticCube[("+", "char", "int")]       = "ERROR"
semanticCube[("-", "char", "int")]       = "ERROR"
semanticCube[("*", "char", "int")]       = "ERROR"
semanticCube[("/", "char", "int")]       = "ERROR"
semanticCube[("=", "char", "int")]       = "ERROR"
semanticCube[("==", "char", "int")]      = "ERROR"
semanticCube[("!=", "char", "int")]      = "ERROR"
semanticCube[("&", "char", "int")]       = "ERROR"
semanticCube[("|", "char", "int")]       = "ERROR"
semanticCube[("<", "char", "int")]       = "ERROR"
semanticCube[(">", "char", "int")]       = "ERROR"
semanticCube[("<=", "char", "int")]      = "ERROR"
semanticCube[(">=", "char", "int")]      = "ERROR"

semanticCube[("+", "char", "float")]     = "ERROR"
semanticCube[("-", "char", "float")]     = "ERROR"
semanticCube[("*", "char", "float")]     = "ERROR"
semanticCube[("/", "char", "float")]     = "ERROR"
semanticCube[("=", "char", "float")]     = "ERROR"
semanticCube[("==", "char", "float")]    = "ERROR"
semanticCube[("!=", "char", "float")]    = "ERROR"
semanticCube[("&", "char", "float")]     = "ERROR"
semanticCube[("|", "char", "float")]     = "ERROR"
semanticCube[("<", "char", "float")]     = "ERROR"
semanticCube[(">", "char", "float")]     = "ERROR"
semanticCube[("<=", "char", "float")]    = "ERROR"
semanticCube[(">=", "char", "float")]    = "ERROR"

semanticCube[("+", "char", "char")]      = "ERROR"
semanticCube[("-", "char", "char")]      = "ERROR"
semanticCube[("*", "char", "char")]      = "ERROR"
semanticCube[("/", "char", "char")]      = "ERROR"
semanticCube[("=", "char", "char")]      = "char"
semanticCube[("==", "char", "char")]     = "bool"
semanticCube[("!=", "char", "char")]     = "bool"
semanticCube[("&", "char", "char")]      = "ERROR"
semanticCube[("|", "char", "char")]      = "ERROR"
semanticCube[("<", "char", "char")]      = "ERROR"
semanticCube[(">", "char", "char")]      = "ERROR"
semanticCube[("<=", "char", "char")]     = "ERROR"
semanticCube[(">=", "char", "char")]     = "ERROR"

semanticCube[("+", "char", "bool")]      = "ERROR"
semanticCube[("-", "char", "bool")]      = "ERROR"
semanticCube[("*", "char", "bool")]      = "ERROR"
semanticCube[("/", "char", "bool")]      = "ERROR"
semanticCube[("=", "char", "bool")]      = "ERROR"
semanticCube[("==", "char", "bool")]     = "ERROR"
semanticCube[("!=", "char", "bool")]     = "ERROR"
semanticCube[("&", "char", "bool")]      = "ERROR"
semanticCube[("|", "char", "bool")]      = "ERROR"
semanticCube[("<", "char", "bool")]      = "ERROR"
semanticCube[(">", "char", "bool")]      = "ERROR"
semanticCube[("<=", "char", "bool")]     = "ERROR"
semanticCube[(">=", "char", "bool")]     = "ERROR"

semanticCube[("+", "bool", "int")]       = "ERROR"
semanticCube[("-", "bool", "int")]       = "ERROR"
semanticCube[("*", "bool", "int")]       = "ERROR"
semanticCube[("/", "bool", "int")]       = "ERROR"
semanticCube[("=", "bool", "int")]       = "ERROR"
semanticCube[("==", "bool", "int")]      = "ERROR"
semanticCube[("!=", "bool", "int")]      = "ERROR"
semanticCube[("&", "bool", "int")]       = "ERROR"
semanticCube[("|", "bool", "int")]       = "ERROR"
semanticCube[("<", "bool", "int")]       = "ERROR"
semanticCube[(">", "bool", "int")]       = "ERROR"
semanticCube[("<=", "bool", "int")]      = "ERROR"
semanticCube[(">=", "bool", "int")]      = "ERROR"

semanticCube[("+", "bool", "float")]     = "ERROR"
semanticCube[("-", "bool", "float")]     = "ERROR"
semanticCube[("*", "bool", "float")]     = "ERROR"
semanticCube[("/", "bool", "float")]     = "ERROR"
semanticCube[("=", "bool", "float")]     = "ERROR"
semanticCube[("==", "bool", "float")]    = "ERROR"
semanticCube[("!=", "bool", "float")]    = "ERROR"
semanticCube[("&", "bool", "float")]     = "ERROR"
semanticCube[("|", "bool", "float")]     = "ERROR"
semanticCube[("<", "bool", "float")]     = "ERROR"
semanticCube[(">", "bool", "float")]     = "ERROR"
semanticCube[("<=", "bool", "float")]    = "ERROR"
semanticCube[(">=", "bool", "float")]    = "ERROR"

semanticCube[("+", "bool", "char")]      = "ERROR"
semanticCube[("-", "bool", "char")]      = "ERROR"
semanticCube[("*", "bool", "char")]      = "ERROR"
semanticCube[("/", "bool", "char")]      = "ERROR"
semanticCube[("=", "bool", "char")]      = "ERROR"
semanticCube[("==", "bool", "char")]     = "ERROR"
semanticCube[("!=", "bool", "char")]     = "ERROR"
semanticCube[("&", "bool", "char")]      = "ERROR"
semanticCube[("|", "bool", "char")]      = "ERROR"
semanticCube[("<", "bool", "char")]      = "ERROR"
semanticCube[(">", "bool", "char")]      = "ERROR"
semanticCube[("<=", "bool", "char")]     = "ERROR"
semanticCube[(">=", "bool", "char")]     = "ERROR"

semanticCube[("+", "bool", "bool")]      = "ERROR"
semanticCube[("-", "bool", "bool")]      = "ERROR"
semanticCube[("*", "bool", "bool")]      = "ERROR"
semanticCube[("/", "bool", "bool")]      = "ERROR"
semanticCube[("=", "bool", "bool")]      = "bool"
semanticCube[("==", "bool", "bool")]     = "bool"
semanticCube[("!=", "bool", "bool")]     = "bool"
semanticCube[("&", "bool", "bool")]      = "bool"
semanticCube[("|", "bool", "bool")]      = "bool"
semanticCube[("<", "bool", "bool")]      = "ERROR"
semanticCube[(">", "bool", "bool")]      = "ERROR"
semanticCube[("<=", "bool", "bool")]     = "ERROR"
semanticCube[(">=", "bool", "bool")]     = "ERROR"

def resultingType(p1, p2, p3):
    key = (p1, p2, p3)
    if key in semanticCube:
        return semanticCube[key]
    else:
        return "Input key incompatible."
